exports.languagesmap=[
    ["aa","Afar"],
    ["ab","Abkhazian"],
    ["ae","Avestan"],
    ["af","Afrikaans"],
    ["ak","Akan"],
    ["am","Amharic"],
    ["an","Aragonese"],
    ["ar","Arabic"],
    ["as","Assamese"],
    ["av","Avaric"],
    ["so","Somali"],
    ["sc","Sardinian"],
    ["ms","Malay"],
    ["tr","Turkish"],
    ["lt","Lithuanian"],
    ["pt","Portuguese"],
    ["en","English"],
    ["pl","Polish"],
    ["ur","Urdu"],
    ["vi","Vietnamese"],
    ["fa","Persian"],
    ["et","Estonian"],
    ["sq","Albanian"],
    ["sk","Slovak"],
    ["mr","Marathi"],
    ["it","Italian"],
    ["eo","Esperanto"],
    ["ko","Korean"],
    ["ay","Aymara"],
    ["az","Azerbaijani"],
    ["ba","Bashkir"],
    ["be","Belarusian"],
    ["bg","Bulgarian"],
    ["bh","Bihari languages"],
    ["bi","Bislama"],
    ["bm","Bambara"],
    ["bn","Bengali"],
    ["bo","Tibetan"],
    ["br","Breton"],
    ["bs","Bosnian"],
    ["ca","Catalan; Valencian"],
    ["ce","Chechen"],
    ["ch","Chamorro"],
    ["cr","Cree"],
    ["cs","Czech"],
    ["cu","Church Slavic; Slavonic;Old Bulgarian"],
    ["cv","Chuvash"],
    ["cy","Welsh"],
    ["da","Danish"],
    ["de","German"],
    ["dv","Divehi; Dhivehi; Maldivian"],
    ["dz","Dzongkha"],
    ["ee","Ewe"],
    ["el","Greek, Modern (1453-)"],
    ["es","Spanish; Castilian"],
    ["et","Estonian"],
    ["eu","Basque"],
    ["ff","Fulah"],
    ["fi","Finnish"],
    ["fz","Fijian"],
    ["fo","Faroese"],
    ["fr","French"],
    ["fy","Western Frisian"],
    ["ga","Irish"],
    ["gu","Gujarati"],
    ["gd","Gaelic; Scottish Gaelic"],
    ["gl","Galician"],
    ["gn","Guarani"],
    ["gv","Manx"],
    ["he","Hebrew"],
    ["hi","Hindi"],
    ["hr","Croatian"],
    ["ha","Hausa"],
    ["ho","Hiri Motu"],
    ["hz","Herero"],
    ["id","Indonesian"],
    ["ia","Interlingua"],
    ["ie","Interlingue; Occidental"],
    ["ig","Igbo"],
    ["ii","Sichuan Yi; Nuosu"],
    ["ik","Inupiaq"],
    ["io","Ido"],
    ["ja","Japanese"],
    ["jv","Javanese"],
    ["kn","Kannada"],
    ["ks","Kashmiri"],
    ["kg","Kongo"],
    ["ki","Kikuyu; Gikuyu"],
    ["kj","Kuanyama; Kwanyama"],
    ["kk","Kazakh"],
    ["kl","Kalaallisut; Greenlandic"],
    ["km","Central Khmer"],
    ["ku","Kurdish"],
    ["kv","Komi"],
    ["kw","Cornish"],
    ["ky","Kirghiz; Kyrgyz"],
    ["la","Latin"],
    ["lb","Luxembourgish; Letzeburgesch"],
    ["lg","Ganda"],
    ["li","Limburgan; Limburger; Limburgish"],
    ["ln","Lingala"],
    ["lo","Lao"],
    ["lt","Lithuanian"],
    ["lu","Luba-Katanga"],
    ["lv","Latvian"],
    ["ml","Malayalam"],
    ["mn","Mongolian"],
    ["mt","Maltese"],
    ["mg","Malagasy"],
    ["mh","Marshallese"],
    ["mi","Maori"],
    ["mk","Macedonian"],
    ["my","Burmese"],
    ["ms","Malay"],
    ["ne","Nepali"],
    ["na","Nauru"],
    ["nb","Norwegian Bokmål"],
    ["nd","Ndebele, North; North Ndebele"],
    ["ng","Ndonga"],
    ["nl","Dutch; Flemish"],
    ["nn","Norwegian Nynorsk"],
    ["no","Norwegian"],
    ["nr","Ndebele, South; South Ndebele"],
    ["nv","Navajo; Navaho"],
    ["ny","Chichewa; Chewa; Nyanja"],
    ["oc","Occitan (post 1500)"],
    ["oj","Ojibwa"],
    ["om","Oromo"],
    ["or","Oriya"],
    ["os","Ossetian; Ossetic"],
    ["pa","Punjabi"],
    ["pi","Pali"],
    ["ps","Pushto; Pashto"],
    ["qu","Quechua"],
    ["rm","Romansh"],
    ["ro","Romanian; Moldavian; Moldovan"],
    ["rw","Kinyarwanda"],
    ["rn","Rundi"],
    ["ru","Russian"],
    ["sa","Sanskrit"],
    ["sc","Sardinian"],
    ["sd","Sindhi"],
    ["se","Northern Sami"],
    ["sg","Sango"],
    ["si","Sinhala; Sinhalese"],
    ["sk","Slovak"],
    ["sl","Slovenian"],
    ["sm","Samoan"],
    ["sn","Shona"],
    ["so","Somali"],
    ["sq","Albanian"],
    ["sr","Serbian"],
    ["ss","Swati"],
    ["st","Sotho, Southern"],
    ["su","Sundanese"],
    ["sv","Swedish"],
    ["sw","Swahili"],
    ["sv","Swedish"],
    ["ta","Tamil"],
    ["te","Telugu"],
    ["tg","Tajik"],
    ["ti","Tigrinya"],
    ["tk","Turkmen"],
    ["tn","Tswana"],
    ["to","Tonga (Tonga Islands)"],
    ["ts","Tsonga"],
    ["tt","Tatar"],
    ["tw","Twi"],
    ["ty","Tahitian"],
    ["th","Thai"],
    ["tl","Tagalog"],
    ["tr","Turkish"],
    ["ug","Uighur; Uyghur"],
    ["uk","Ukrainian"],
    ["ur","Urdu"],
    ["uz","Uzbek"],
    ["ve","Venda"],
    ["vo","Volapük"],   
    ["wa","Walloon"],
    ["wo","Wolof"],
    ["xh","Xhosa"],
    ["yi","Yiddish"],
    ["yo","Yoruba"],
    ["za","Zhuang; Chuang"],
    ["zh","Chinese"],
    ["zu","Zulu"],
    ["ve","venda"]
]