module.exports = {
    ap : 'Andhra Pradesh',
    ar : 'Arunachal Pradesh',
    as : 'Assam',
    br : 'Bihar',
    cg : 'Chhattisgarh',
    ga : 'Goa',
    gj : 'Gujarat',
    hr : 'Haryana',
    hp : 'Himachal Pradesh',
    jk : 'Jammu and Kashmir',
    jh : 'Jharkhand',
    ka : 'Karnataka',
    kl : 'Kerala',
    mp : 'Madhya Pradesh',
    mh : 'Maharashtra',
    mn : 'Manipur',
    ml : 'Meghalaya',
    mz : 'Mizoram',
    nl : 'Nagaland',
    or : 'Orissa',
    pb : 'Punjab',
    rj : 'Rajasthan',
    sk : 'Sikkim',
    tg: 'Telangana',
    tn : 'Tamil Nadu',
    tr : 'Tripura',
    uk : 'Uttarakhand',
    up : 'Uttar Pradesh',
    wb : 'West Bengal',
    tn : 'Tamil Nadu',
    tr : 'Tripura',
    an : 'Andaman and Nicobar Islands',
    ch : 'Chandigarh',
    dh : 'Dadra and Nagar Haveli',
    dd : 'Daman and Diu',
    dl : 'Delhi',
    ld : 'Lakshadweep',
    py : 'Pondicherry'
}