// auth
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const NETWORK_ERROR = 'NETWORK_ERROR';

// ManageAds
export const MANAGEADS_LOADING = 'MANAGEADS_LOADING';
export const MANAGEADS_SEARCH = 'MANAGEADS_SEARCH';
export const MANAGEADS_LOADDED = 'MANAGEADS_LOADDED';
export const MANAGEADS_SORT_NAME = 'MANAGEADS_SORT_NAME';
export const MANAGEADS_PAGINATION = 'MANAGEADS_PAGINATION';
export const MANAGEADS_LOAD_ERROR = 'MANAGEADS_LOAD_ERROR';

// ManageBundles
export const MANAGEBUNDLES_LOADING = 'MANAGEBUNDLES_LOADING';
export const MANAGEBUNDLES_SEARCH = 'MANAGEBUNDLES_SEARCH';
export const MANAGEBUNDLES_LOADDED = 'MANAGEBUNDLES_LOADDED';
export const MANAGEBUNDLES_SORT_NAME = 'MANAGEBUNDLES_SORT_NAME';
export const MANAGEBUNDLES_PAGINATION = 'MANAGEBUNDLES_PAGINATION';
export const MANAGEBUNDLES_LOAD_ERROR = 'MANAGEBUNDLES_LOAD_ERROR';

// report loading
export const REPORT_ID_ = 'REPORT_ID_';
export const REPORT_LOADING = 'REPORT_LOADING';
export const REPORT_BASE_LOADED = 'REPORT_BASE_LOADED';
export const REPORT_BASE_LOADED_CLIENT = 'REPORT_BASE_LOADED_CLIENT';
export const REPORT_LOADED = 'REPORT_LOADED';
export const REPORT_LOADED_CLIENT = 'REPORT_LOADED_CLIENT';
export const REPORT_SPENT_LOADED = 'REPORT_SPENT_LOADED';
export const REPORT_ERROR = 'REPORT_ERROR';
export const REPORT_CLEAR = 'REPORT_CLEAR';
export const REPORT_READY = 'REPORT_READY';

// SORTING DATA IN TABLES
export const DATA_SORTED = 'DATA_SORTED';
export const DATA_SORT_ERROR = 'DATA_SORT_ERROR';

// Currency ratio
export const RATIO_UPDATED = 'RATIO_UPDATED';
export const RATIO_CLEAR = 'RATIO_CLEAR';
export const RATIO_ERROR = 'RATIO_ERROR';
export const RATIO_LOADING = 'RATIO_LOADING';

//Quartile
export const QUARTILE_LOADED = 'QUARTILE_LOADED';
export const QUARTILE_LOADING = 'QUARTILE_LOADING';
export const QUARTILE_ERROR = 'QUARTILE_ERROR';

//Quartile
export const FREQUENCY_LOADED = 'FREQUENCY_LOADED';
export const FREQUENCY_LOADING = 'FREQUENCY_LOADING';
export const FREQUENCY_ERROR = 'FREQUENCY_ERROR';

// consolidate reports
export const PUBLISHERDATA_LOADED = 'PUBLISHERDATA_LOADED';
export const PUBLISHERDATA_LOADING = 'PUBLISHERDATA_LOADING';
export const PUBLISHERDATA_ERROR = 'PUBLISHERDATA_ERROR';
export const PUBLISHERDATA_CLEAR = 'PUBLISHERDATA_CLEAR';
export const PUBLISHERDATA_SEARCH_AUDIO = 'PUBLISHERDATA_SEARCH_AUDIO';
export const PUBLISHERDATA_SORT_AUDIO = 'PUBLISHERDATA_SORT_AUDIO';
export const PUBLISHERDATA_PAGINATION_AUDIO = 'PUBLISHERDATA_PAGINATION_AUDIO';
export const PUBLISHERDATA_SEARCH_DISPLAY = 'PUBLISHERDATA_SEARCH_DISPLAY';
export const PUBLISHERDATA_SORT_DISPLAY = 'PUBLISHERDATA_SORT_DISPLAY';
export const PUBLISHERDATA_PAGINATION_DISPLAY = 'PUBLISHERDATA_PAGINATION_DISPLAY';
export const PUBLISHERDATA_SEARCH_VIDEO = 'PUBLISHERDATA_SEARCH_VIDEO';
export const PUBLISHERDATA_SORT_VIDEO = 'PUBLISHERDATA_SORT_VIDEO';
export const PUBLISHERDATA_PAGINATION_VIDEO = 'PUBLISHERDATA_PAGINATION_VIDEO';
