// auth
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const NETWORK_ERROR = 'NETWORK_ERROR';

// ManageAds
export const MANAGEADS_LOADING = 'MANAGEADS_LOADING';
export const MANAGEADS_SEARCH = 'MANAGEADS_SEARCH';
export const MANAGEADS_LOADDED = 'MANAGEADS_LOADDED';
export const MANAGEADS_SORT_NAME = 'MANAGEADS_SORT_NAME';
export const MANAGEADS_LOAD_ERROR = 'MANAGEADS_LOAD_ERROR';

// ManageBundles
export const MANAGEBUNDLES_LOADING = 'MANAGEBUNDLES_LOADING';
export const MANAGEBUNDLES_SEARCH = 'MANAGEBUNDLES_SEARCH';
export const MANAGEBUNDLES_LOADDED = 'MANAGEBUNDLES_LOADDED';
export const MANAGEBUNDLES_SORT_NAME = 'MANAGEBUNDLES_SORT_NAME';
export const MANAGEBUNDLES_LOAD_ERROR = 'MANAGEBUNDLES_LOAD_ERROR';

// report loading
export const REPORT_ID_ = 'REPORT_ID_';
export const REPORT_LOADING = 'REPORT_LOADING';
export const REPORT_BASE_LOADED = 'REPORT_BASE_LOADED';
export const REPORT_LOADED = 'REPORT_LOADED';
export const REPORT_SPENT_LOADED = 'REPORT_SPENT_LOADED';
export const REPORT_ERROR = 'REPORT_ERROR';

// SORTING DATA IN TABLES
export const DATA_SORTED = 'DATA_SORTED';
export const DATA_SORT_ERROR = 'DATA_SORT_ERROR';

// Currency ratio
export const RATIO_UPDATED = 'RATIO_UPDATED';
export const RATIO_CLEAR = 'RATIO_CLEAR';
export const RATIO_ERROR = 'RATIO_ERROR';
export const RATIO_LOADING = 'RATIO_LOADING';
